name: grokk_model
mode: mlp
#modeselect:transformer/lstm/mlp
transformer_config:
  max_length: 5
  heads: 4
  attn_dim: 32
  intermediate_dim: 512
  num_blocks: 2
  block_repeats: 1
  dropout: 0
  pre_norm: true
lstm_config:
  intermediate_dim: 512
  num_layers: 1
  dropout: 0.1
  bidirectional: True
mlp_config:
  num_layers: 2
  intermediate_dim: 512
  add_bias: True
  norm_method: batchnorm
  num_p: 2

checkpoint_path: null
strict_load: true
