name: grokk_model
mode: transformer
#modeselect:transformer/lstm/mlp
transformer_config:
  max_length: 5
  heads: 4
  hidden_dim: 99
  attn_dim: 32
  intermediate_dim: 512
  num_blocks: 2
  block_repeats: 1
  dropout: 0.1
  pre_norm: true
lstm_config:
  hidden_dim: 99
  intermediate_dim: 512
  num_layers: 1
  dropout: 0.1
  bidirectional: True
mlp_config:
  hidden_dim: 99
  num_layers: 5
  intermediate_dim: 128
  add_bias: True
  norm_method: batchnorm
  num_p: 2

checkpoint_path: null
strict_load: true
