name: grokk_model
mode: transformer
#在这里选取模型的类型:transformer/lstm/mlp，下面是对应模型的结构参数
transformer_config:
  max_length: 5
#保持这个等于2*num_p+1
  heads: 4
  attn_dim: 32
  intermediate_dim: 512
  num_blocks: 2
  block_repeats: 1
  dropout: 0
  pre_norm: true
lstm_config:
  intermediate_dim: 512
  num_layers: 1
  dropout: 0
  bidirectional: True
mlp_config:
  num_layers: 2
  intermediate_dim: 512
  add_bias: True
  norm_method: batchnorm
  num_p: 2
#保持这个等于num_p

checkpoint_path: null
strict_load: true
